# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

detect_wind_cpp <- function(input_file_directory, output_directory, tree_locs, verbose = 0L) {
    .Call(`_ARUtoolsExtra_detect_wind_cpp`, input_file_directory, output_directory, tree_locs, verbose)
}

